### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bradley-r**
Back once again!

Been through 5 or so distros in the past month trying to find something new, and I think I've found a comfortable option - _you'll be pleased to know srsrs worked fine on each one_. Having settled back down, I got back to tweaking (and, of course, flying) DCS, specifically with headtracking. I'm working on an extension to the guide explaining camera configuration, and I've also added a table of contents that allows anyone that needs to fix common problems (after an update, for example) without scrolling through the install instructions every time.

I've added the camera explanation, and will work on the instructions as time allows. I've also [found the exact issue](https://github.com/opentrack/opentrack/issues/1236) I was having with Opentrack, so can further revise the note on it before merging.

### CODE REVIEW

**Comment by bradley-r** [comment]
Going to add a note here: I've started a repo where I'll post any tips and fixes about (HOTAS) controllers on Linux here. Barren for now, but I may be so bold I might add it as a resource under 'fixes' (or elsewhere, if you'd like) when it's complete. I know I'd have loved all the information I plan to add when I started out, so I'm sure it would be of some use. Will add camera config tomorrow.

**Comment by bradley-r** [comment]
New content done; will get the controls repo up and running then mark ready. Summary:

- Added table of contents.
- Added instructions on using DCS-Scratchpad.
- Added instructions (and image) on headtracking camera config.
- Added link to controls repo in the case anyone finds this guide whilst troubleshooting.
- Opentrack description updated with explanation of the error and how to work around it.

**Comment by bradley-r** [comment]
Unless I've missed anything, I think this version is all good to go. Marking ready for review.

**Comment by TheZoq2** [comment]
Excelent work, thanks!

Looking at the diff here, it seems like the images are empty. As far as I can tell, they work on your repo so I'm not sure if it's a github bug :thinking:

**Comment by bradley-r** [comment]
> Looking at the diff here, it seems like the images are empty. As far as I can tell, they work on your repo so I'm not sure if it's a github bug.

That's odd; I used relative links with the thought that GitHub would automatically edit them when pulling, but that might not be the case - I'll try direct instead.

**Comment by TheZoq2** [comment]
Relative links in the markdown? That should be no problem. I meant the "empty file" here:

image

**Comment by bradley-r** [comment]
Ah, understood. Not sure why they appear empty though - they show up fine in diff and rich views my end:

Screenshot_20210304_123018

Screenshot_20210304_123206

I have noticed that when viewing from this pull request, the images already link to this repo rather than mine - they are expecting images here: https://github.com/TheZoq2/dcs_on_linux/raw/master/images/_xyz_, which  obviously aren't present yet. Viewing directly from my repo works as you say.

**Comment by bradley-r** [comment]
Given nothing has changed with time, I'll try direct links just in case - I think it would work if merged currently (as the images would move to the address the pull is expecting) but if they appear directly it could be merged then changed back to relative linking. 

Screenshot_20210305_213921

**Comment by bradley-r** [comment]
Okay, they appear (for me) when viewed from the pull request now. I've found where you pointed out the files being 'empty', but when viewed with rich enabled they show up fine on my end.

Screenshot_20210305_214742

**Comment by TheZoq2** [comment]
Yea, worst case scenario, we can just revert the merge

**Comment by bradley-r** [comment]
All appears fine on my end; it must have just been something related to the way GitHub handles pull requests. Either way, happy to help as always - I'll be adding to the controller fixes when time allows.

**Pull request merged**
